"""Public model, configuration, and pinned provenance for TimeMixer."""

from .configs import TimeMixerConfig
from .TimeMixer import TimeMixerModel

from .provenance import (
    TIMEMIXER_PAPER_TITLE,
    TIMEMIXER_PAPER_URL,
    TIMEMIXER_UPSTREAM_COMMIT,
    TIMEMIXER_UPSTREAM_FILES,
    TIMEMIXER_UPSTREAM_LICENSE,
    TIMEMIXER_UPSTREAM_LICENSE_FILE,
    TIMEMIXER_UPSTREAM_MANIFEST_FILE,
    TIMEMIXER_UPSTREAM_MODEL_COMMIT,
    TIMEMIXER_UPSTREAM_NOTICE_PRESENT,
    TIMEMIXER_UPSTREAM_REPOSITORY,
    TIMEMIXER_UPSTREAM_TREE,
)

__all__ = [
    "TimeMixerConfig",
    "TimeMixerModel",
    "TIMEMIXER_PAPER_TITLE",
    "TIMEMIXER_PAPER_URL",
    "TIMEMIXER_UPSTREAM_COMMIT",
    "TIMEMIXER_UPSTREAM_FILES",
    "TIMEMIXER_UPSTREAM_LICENSE",
    "TIMEMIXER_UPSTREAM_LICENSE_FILE",
    "TIMEMIXER_UPSTREAM_MANIFEST_FILE",
    "TIMEMIXER_UPSTREAM_MODEL_COMMIT",
    "TIMEMIXER_UPSTREAM_NOTICE_PRESENT",
    "TIMEMIXER_UPSTREAM_REPOSITORY",
    "TIMEMIXER_UPSTREAM_TREE",
]
